name: "Prepare klogg version env var"
description: ""
runs:
  using: "composite"
  steps:
    - name: Set klogg version
      shell: sh
      run: |
        cmake -DVERSION_ENV_FILE="$GITHUB_ENV" -P cmake/ExportCiVersion.cmake
