if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()
file(READ "${SOURCE_ROOT}/CMakePresets.json" presets)
function(find_preset section name output)
  string(JSON count LENGTH "${presets}" "${section}")
  math(EXPR last "${count} - 1")
  foreach(index RANGE 0 ${last})
    string(JSON candidate GET "${presets}" "${section}" ${index} name)
    if(candidate STREQUAL name)
      string(JSON preset GET "${presets}" "${section}" ${index})
      set(${output} "${preset}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "Missing ${section}: ${name}")
endfunction()

# 发布验收预设固定为 ninja-ui-release：Release 构建、启用 UI 专项测试，
# 且测试预设不带 filter（跑全部已注册测试）。Windows 与 Linux 共用同一
# Ninja 预设，本地与 CI 的生成器一致。
set(release_preset ninja-ui-release)

find_preset(configurePresets ${release_preset} configure_entry)
string(JSON build_type GET "${configure_entry}" cacheVariables CMAKE_BUILD_TYPE)
if(NOT build_type STREQUAL "Release")
  message(FATAL_ERROR "${release_preset} must configure a Release build, got ${build_type}")
endif()

foreach(section IN ITEMS buildPresets testPresets)
  find_preset(${section} ${release_preset} entry)
  string(JSON configure GET "${entry}" configurePreset)
  if(NOT configure STREQUAL release_preset)
    message(FATAL_ERROR "${section} must use the ${release_preset} configure preset")
  endif()
endforeach()
string(JSON filter ERROR_VARIABLE filter_error GET "${entry}" filter)
if(NOT filter_error)
  message(FATAL_ERROR "Release acceptance must run the complete registered test suite")
endif()

find_preset(workflowPresets ${release_preset} workflow)
set(expected_names ${release_preset} ${release_preset} ${release_preset})
set(expected_types configure build test)
string(JSON count LENGTH "${workflow}" steps)
if(NOT count EQUAL 3)
  message(FATAL_ERROR "Release workflow must configure, build and test")
endif()
foreach(index RANGE 0 2)
  string(JSON name GET "${workflow}" steps ${index} name)
  string(JSON type GET "${workflow}" steps ${index} type)
  list(GET expected_names ${index} expected_name)
  list(GET expected_types ${index} expected_type)
  if(NOT name STREQUAL expected_name OR NOT type STREQUAL expected_type)
    message(FATAL_ERROR "Invalid Release workflow step ${index}")
  endif()
endforeach()
