if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()
file(READ "${SOURCE_ROOT}/CMakePresets.json" presets)
function(find_preset section name output)
  string(JSON count LENGTH "${presets}" "${section}")
  math(EXPR last "${count} - 1")
  foreach(index RANGE 0 ${last})
    string(JSON candidate GET "${presets}" "${section}" ${index} name)
    if(candidate STREQUAL name)
      string(JSON preset GET "${presets}" "${section}" ${index})
      set(${output} "${preset}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "Missing ${section}: ${name}")
endfunction()
foreach(section IN ITEMS buildPresets testPresets)
  find_preset(${section} windows-vs2026-ui-release entry)
  string(JSON config GET "${entry}" configuration)
  string(JSON configure GET "${entry}" configurePreset)
  if(NOT config STREQUAL "Release" OR NOT configure STREQUAL "windows-vs2026-ui")
    message(FATAL_ERROR "${section} must use the Release UI configuration")
  endif()
endforeach()
string(JSON filter ERROR_VARIABLE filter_error GET "${entry}" filter)
if(NOT filter_error)
  message(FATAL_ERROR "Release acceptance must run the complete registered test suite")
endif()
find_preset(workflowPresets windows-vs2026-ui-release workflow)
set(expected_names windows-vs2026-ui windows-vs2026-ui-release windows-vs2026-ui-release)
set(expected_types configure build test)
string(JSON count LENGTH "${workflow}" steps)
if(NOT count EQUAL 3)
  message(FATAL_ERROR "Release workflow must configure, build and test")
endif()
foreach(index RANGE 0 2)
  string(JSON name GET "${workflow}" steps ${index} name)
  string(JSON type GET "${workflow}" steps ${index} type)
  list(GET expected_names ${index} expected_name)
  list(GET expected_types ${index} expected_type)
  if(NOT name STREQUAL expected_name OR NOT type STREQUAL expected_type)
    message(FATAL_ERROR "Invalid Release workflow step ${index}")
  endif()
endforeach()
