cmake_minimum_required(VERSION 3.24)
if(DEFINED CASE)
  include("${SOURCE_ROOT}/cmake/ZzUpdateFeedConfiguration.cmake")
  string(REPEAT "a" 64 key)
  set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:${key}")
  set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates.example.invalid")
  if(CASE STREQUAL "duplicate")
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:${key};release:${key}")
  elseif(CASE STREQUAL "short")
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:ab")
  elseif(CASE STREQUAL "uppercase")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "Updates.example.invalid")
  elseif(CASE STREQUAL "badlabel")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "-updates.example.invalid")
  elseif(CASE STREQUAL "emptylabel")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates..invalid")
  elseif(CASE STREQUAL "trailingdot")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates.invalid.")
  elseif(CASE STREQUAL "injection")
    set(ZZLOGG_UPDATE_STABLE_URL "https://updates.invalid/\"; injected(); //")
  endif()
  if(CASE MATCHES "^github")
    set(ZZLOGG_ENABLE_GITHUB_FEED ON)
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "")
    if(CASE STREQUAL "github_custom")
      set(ZZLOGG_UPDATE_STABLE_URL "https://custom.example.invalid/stable")
    endif()
  elseif(CASE STREQUAL "disabled")
    set(ZZLOGG_ENABLE_GITHUB_FEED OFF)
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "")
  endif()
  zzlogg_configure_update_feed("${OUTPUT}")
  if(CASE MATCHES "^github" OR CASE STREQUAL "disabled")
    file(READ "${OUTPUT}" generated)
    set(url "https://raw.githubusercontent.com/jackfahdin/ZzLogg/update-feed/stable.json")
    if(CASE STREQUAL "github_custom")
      set(url "https://custom.example.invalid/stable")
    elseif(CASE STREQUAL "disabled")
      set(url "")
    endif()
    string(HEX "${url}" expected)
    string(FIND "${generated}" "Stable[]=\"${expected}\"" found)
    if(found EQUAL -1)
      message(FATAL_ERROR "Unexpected default update URL for ${CASE}")
    endif()
    if(CASE MATCHES "^github")
      file(READ "${SOURCE_ROOT}/packaging/update/github-public-key.json" public)
      string(JSON key_id GET "${public}" keyId)
      string(JSON key_hex GET "${public}" publicKey)
      string(HEX "${key_id}:${key_hex}" expected)
      string(FIND "${generated}" "Keys[]=\"${expected}\"" found)
      if(found EQUAL -1)
        message(FATAL_ERROR "GitHub public key was not embedded")
      endif()
    endif()
  endif()
  if(CASE STREQUAL "injection")
    file(READ "${OUTPUT}" generated)
    if(generated MATCHES "injected")
      message(FATAL_ERROR "Unescaped URL entered C++ source")
    endif()
  endif()
  return()
endif()
foreach(case github github_custom disabled valid duplicate short uppercase badlabel emptylabel trailingdot injection)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" "-DSOURCE_ROOT=${SOURCE_ROOT}"
    "-DOUTPUT=${BINARY_ROOT}/feed-${case}.h" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(case MATCHES "^github" OR case STREQUAL "disabled" OR case STREQUAL "valid" OR case STREQUAL "injection")
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Valid configuration rejected: ${case}: ${error}")
    endif()
  elseif(result EQUAL 0)
    message(FATAL_ERROR "Invalid configuration accepted: ${case}")
  endif()
endforeach()
