cmake_minimum_required(VERSION 3.24)
if(DEFINED CASE)
  include("${SOURCE_ROOT}/cmake/ZzUpdateFeedConfiguration.cmake")
  string(REPEAT "a" 64 key)
  set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:${key}")
  set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates.example.invalid")
  if(CASE STREQUAL "duplicate")
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:${key};release:${key}")
  elseif(CASE STREQUAL "short")
    set(ZZLOGG_UPDATE_PUBLIC_KEYS "release:ab")
  elseif(CASE STREQUAL "uppercase")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "Updates.example.invalid")
  elseif(CASE STREQUAL "badlabel")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "-updates.example.invalid")
  elseif(CASE STREQUAL "emptylabel")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates..invalid")
  elseif(CASE STREQUAL "trailingdot")
    set(ZZLOGG_UPDATE_ALLOWED_HOSTS "updates.invalid.")
  elseif(CASE STREQUAL "injection")
    set(ZZLOGG_UPDATE_STABLE_URL "https://updates.invalid/\"; injected(); //")
  endif()
  zzlogg_configure_update_feed("${OUTPUT}")
  if(CASE STREQUAL "injection")
    file(READ "${OUTPUT}" generated)
    if(generated MATCHES "injected")
      message(FATAL_ERROR "Unescaped URL entered C++ source")
    endif()
  endif()
  return()
endif()
foreach(case valid duplicate short uppercase badlabel emptylabel trailingdot injection)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" "-DSOURCE_ROOT=${SOURCE_ROOT}"
    "-DOUTPUT=${BINARY_ROOT}/feed-${case}.h" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(case STREQUAL "valid" OR case STREQUAL "injection")
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Valid configuration rejected: ${case}: ${error}")
    endif()
  elseif(result EQUAL 0)
    message(FATAL_ERROR "Invalid configuration accepted: ${case}")
  endif()
endforeach()
