string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef transaction)
set(isolated "${CMAKE_CURRENT_BINARY_DIR}/isolated-${transaction}")
file(MAKE_DIRECTORY "${isolated}")
file(COPY "${EXECUTABLE}" DESTINATION "${isolated}")
get_filename_component(name "${EXECUTABLE}" NAME)
set(program "${isolated}/${name}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PATH=$ENV{SystemRoot}/System32" "${program}"
  WORKING_DIRECTORY "${isolated}" RESULT_VARIABLE result TIMEOUT 5)
if(NOT result EQUAL 41)
  message(FATAL_ERROR "Missing bootstrap must return BootstrapRejected (41), got ${result}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PATH=$ENV{SystemRoot}/System32" "${program}" --installer arbitrary.exe
  WORKING_DIRECTORY "${isolated}" RESULT_VARIABLE result TIMEOUT 5)
if(NOT result EQUAL 41)
  message(FATAL_ERROR "Arbitrary installer arguments must be rejected, got ${result}")
endif()
execute_process(COMMAND "${program}" 18446744073709551616 RESULT_VARIABLE result TIMEOUT 5)
if(NOT result EQUAL 41)
  message(FATAL_ERROR "Invalid inherited-handle argument must reject without hanging: ${result}")
endif()
file(REMOVE "${program}")
# Only this freshly created, now empty test directory is removed.
execute_process(COMMAND "${CMAKE_COMMAND}" -E remove_directory "${isolated}" RESULT_VARIABLE cleaned)
if(NOT cleaned EQUAL 0)
  message(FATAL_ERROR "Could not clean isolated gate fixture")
endif()
