if(NOT IS_ABSOLUTE "${TEST_ROOT}" OR NOT EXISTS "${TOOL}")
  message(FATAL_ERROR "Test requires an absolute build-tree path and tool")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(run "${TEST_ROOT}/${run_id}")
file(MAKE_DIRECTORY "${run}")
set(fixture "${run}/manifest.json")
execute_process(COMMAND "${TOOL}" generate --output "${fixture}" RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT EXISTS "${fixture}")
  message(FATAL_ERROR "Fixture generation failed: ${result}")
endif()
execute_process(COMMAND "${TOOL}" verify --input "${fixture}" --now 1800000000 RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Valid fixture rejected: ${result}")
endif()
file(SHA256 "${fixture}" before)
execute_process(COMMAND "${TOOL}" generate --output "${fixture}" RESULT_VARIABLE result)
file(SHA256 "${fixture}" after)
if(result EQUAL 0 OR NOT before STREQUAL after)
  message(FATAL_ERROR "Existing file was not preserved")
endif()
file(READ "${fixture}" envelope)
string(JSON signature GET "${envelope}" signature)
string(SUBSTRING "${signature}" 0 1 first)
string(SUBSTRING "${signature}" 1 -1 tail)
if(first STREQUAL "A")
  set(first B)
else()
  set(first A)
endif()
string(JSON corrupt SET "${envelope}" signature "\"${first}${tail}\"")
file(WRITE "${run}/corrupt.json" "${corrupt}")
execute_process(COMMAND "${TOOL}" verify --input "${run}/corrupt.json" --now 1800000000 RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Corrupt signature accepted")
endif()
execute_process(COMMAND "${TOOL}" verify --input "${fixture}" --now 1800003600 RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Expired fixture accepted")
endif()
foreach(invalid_now "-1" "1x" "9223372036854775808")
  execute_process(COMMAND "${TOOL}" verify --input "${fixture}" --now "${invalid_now}" RESULT_VARIABLE result)
  if(result EQUAL 0)
    message(FATAL_ERROR "Invalid timestamp accepted")
  endif()
endforeach()
execute_process(COMMAND "${TOOL}" RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Missing arguments accepted")
endif()
string(REPEAT "x" 262145 oversized)
file(WRITE "${run}/oversized.json" "${oversized}")
execute_process(COMMAND "${TOOL}" verify --input "${run}/oversized.json" --now 1800000000 RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Oversized input accepted")
endif()
