if(NOT DEFINED CHECK_SCRIPT OR NOT DEFINED SETTINGS_ROOT
   OR NOT DEFINED SETTINGS_SUFFIX)
  message(FATAL_ERROR "CHECK_SCRIPT, SETTINGS_ROOT and SETTINGS_SUFFIX are required")
endif()

include("${CHECK_SCRIPT}")
assert_ui2_isolated_settings("${SETTINGS_ROOT}" "${SETTINGS_SUFFIX}")
