get_filename_component(main_name "${MAIN_APP}" NAME)
get_filename_component(runtime_dir_name "${RUNTIME_DIR}" NAME)

if(NOT DEFINED EXECUTABLE_SUFFIX)
  message(FATAL_ERROR "EXECUTABLE_SUFFIX is required")
endif()

if(NOT main_name STREQUAL "ZzLogg${EXECUTABLE_SUFFIX}")
  message(FATAL_ERROR "Expected only ZzLogg${EXECUTABLE_SUFFIX}, got ${main_name}")
endif()
if(TARGET_PORTABLE_EXISTS OR TARGET_UI2_EXISTS)
  message(FATAL_ERROR "Separate portable/UI2 GUI targets must not exist")
endif()
if(NOT GREP_EXCLUDED_FROM_ALL)
  message(FATAL_ERROR "klogg_grep must remain EXCLUDE_FROM_ALL")
endif()

if(NOT runtime_dir_name STREQUAL "ZzLogg-runtime")
  message(FATAL_ERROR "Expected runtime directory ZzLogg-runtime, got ${runtime_dir_name}")
endif()
if(NOT EXISTS "${RUNTIME_DIR}/ZzLogg${EXECUTABLE_SUFFIX}")
  message(FATAL_ERROR "Runtime directory is missing ZzLogg${EXECUTABLE_SUFFIX}")
endif()
