if(NOT DEFINED BUILD_DIRECTORY OR NOT DEFINED INSTALL_PREFIX OR NOT DEFINED CONFIG)
  message(FATAL_ERROR "BUILD_DIRECTORY, INSTALL_PREFIX, and CONFIG are required")
endif()
file(REMOVE_RECURSE "${INSTALL_PREFIX}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIRECTORY}"
  --prefix "${INSTALL_PREFIX}" --config "${CONFIG}"
  RESULT_VARIABLE install_result OUTPUT_VARIABLE install_output ERROR_VARIABLE install_error)
if(NOT install_result EQUAL 0)
  message(FATAL_ERROR "Staged install failed:\n${install_output}\n${install_error}")
endif()

set(zz_targets ZzCore ZzWindowKit ZzFluentFoundation ZzFluentUI ZzLog)
if(WIN32_CONTRACT)
  set(app "${INSTALL_PREFIX}/bin/ZzLogg.exe")
  foreach(target IN LISTS zz_targets)
    list(APPEND closure "${INSTALL_PREFIX}/bin/${target}.dll")
  endforeach()
else()
  set(app "${INSTALL_PREFIX}/bin/ZzLogg")
  foreach(target IN LISTS zz_targets)
    file(GLOB match "${INSTALL_PREFIX}/lib/*${target}*${SHARED_LIBRARY_SUFFIX}*")
    if(NOT match)
      message(FATAL_ERROR "Staged install is missing ${target} shared library")
    endif()
  endforeach()
endif()
if(NOT EXISTS "${app}")
  message(FATAL_ERROR "Staged install is missing ${app}")
endif()
foreach(file IN LISTS closure)
  if(NOT EXISTS "${file}")
    message(FATAL_ERROR "Staged install is missing runtime closure file: ${file}")
  endif()
endforeach()
