add_subdirectory(klogg_version)
add_subdirectory(logging)
add_subdirectory(utils)
add_subdirectory(settings)
add_subdirectory(storage)
add_subdirectory(support)
add_subdirectory(regex)
add_subdirectory(logdata)
add_subdirectory(filewatch)
add_subdirectory(update)
add_subdirectory(updateqt)
add_subdirectory(ui)
add_subdirectory(app)
