# Export the same display version used by CPack and the application.
if(NOT DEFINED SOURCE_ROOT)
  get_filename_component(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED VERSION_ENV_FILE OR VERSION_ENV_FILE STREQUAL "")
  message(FATAL_ERROR "VERSION_ENV_FILE is required")
endif()
file(READ "${SOURCE_ROOT}/CMakeLists.txt" project_file)
string(REGEX MATCH "\n[ \t]*VERSION[ \t]+([0-9]+\\.[0-9]+\\.[0-9]+)[ \t\r]*\n" version_match "${project_file}")
if(NOT version_match)
  message(FATAL_ERROR "Cannot read project version from CMakeLists.txt")
endif()
set(project_version "${CMAKE_MATCH_1}")
include("${CMAKE_CURRENT_LIST_DIR}/ZzLoggVersion.cmake")
zzlogg_parse_version("${project_version}")
file(APPEND "${VERSION_ENV_FILE}" "KLOGG_VERSION=${ZZLOGG_DISPLAY_VERSION}\n")
