include("${CMAKE_CURRENT_LIST_DIR}/ZzLoggVersion.cmake")

if(NOT "${BUILD_VERSION}" STREQUAL "")
  zzlogg_parse_version("${BUILD_VERSION}")
else()
  zzlogg_parse_version("${PROJECT_VERSION}")
endif()
set(PROJECT_VERSION_MAJOR "${ZZLOGG_VERSION_COMPONENT_0}")
set(PROJECT_VERSION_MINOR "${ZZLOGG_VERSION_COMPONENT_1}")
set(PROJECT_VERSION_PATCH "${ZZLOGG_VERSION_COMPONENT_2}")
set(PROJECT_VERSION_TWEAK "${ZZLOGG_VERSION_COMPONENT_3}")
set(PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
if(NOT "${BUILD_NUMBER}" STREQUAL "")
  zzlogg_parse_version("${PROJECT_VERSION}.${BUILD_NUMBER}")
  set(PROJECT_VERSION_TWEAK "${ZZLOGG_VERSION_COMPONENT_3}")
endif()

message("Project version is ${PROJECT_VERSION}")
message("Project version tweak is ${PROJECT_VERSION_TWEAK}")

include_directories(${CMAKE_BINARY_DIR}/generated)

include(win32_rc)

generate_product_version(
  ProductVersionResourceFiles
  NAME
  "${ZZLOGG_PRODUCT_NAME}"
  ORIGINAL_FILENAME
  "${ZZLOGG_PRODUCT_NAME}.exe"
  ICON
  "${CMAKE_SOURCE_DIR}/Resources/ZzLogg.ico"
  FILE_DESCRIPTION
  "${ZZLOGG_PRODUCT_DESCRIPTION}"
  VERSION_MAJOR
  ${PROJECT_VERSION_MAJOR}
  VERSION_MINOR
  ${PROJECT_VERSION_MINOR}
  VERSION_PATCH
  ${PROJECT_VERSION_PATCH}
  VERSION_REVISION
  ${PROJECT_VERSION_TWEAK}
  VERSION_TEXT
  "${ZZLOGG_DISPLAY_VERSION}"
  COMPANY_NAME
  "${ZZLOGG_VENDOR}"
  COMPANY_COPYRIGHT
  ${COPYRIGHT}
)

generate_product_version(
  GrepProductVersionResourceFiles
  OUTPUT_DIRECTORY
  "${CMAKE_BINARY_DIR}/generated/klogg_grep"
  NAME
  "${ZZLOGG_PRODUCT_NAME}"
  ORIGINAL_FILENAME
  "${ZZLOGG_PRODUCT_NAME}_grep.exe"
  ICON
  "${CMAKE_SOURCE_DIR}/Resources/ZzLogg.ico"
  FILE_DESCRIPTION
  "${ZZLOGG_PRODUCT_DESCRIPTION}"
  VERSION_MAJOR
  ${PROJECT_VERSION_MAJOR}
  VERSION_MINOR
  ${PROJECT_VERSION_MINOR}
  VERSION_PATCH
  ${PROJECT_VERSION_PATCH}
  VERSION_REVISION
  ${PROJECT_VERSION_TWEAK}
  VERSION_TEXT
  "${ZZLOGG_DISPLAY_VERSION}"
  COMPANY_NAME
  "${ZZLOGG_VENDOR}"
  COMPANY_COPYRIGHT
  ${COPYRIGHT}
)

set(AllProductVersionResourceFiles
  ${ProductVersionResourceFiles}
  ${GrepProductVersionResourceFiles}
)

add_custom_target(
  generate_version ALL
  COMMAND ${CMAKE_COMMAND} -DBUILD_VERSION=${PROJECT_VERSION}.${PROJECT_VERSION_TWEAK} -P
          ${CMAKE_SOURCE_DIR}/cmake/generate_version_h.cmake
  DEPENDS ${AllProductVersionResourceFiles}
  SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/cmake/generate_version_h.cmake
          ${CMAKE_CURRENT_SOURCE_DIR}/cmake/version_info.h.in ${CMAKE_CURRENT_SOURCE_DIR}/cmake/version_resource.rc.in
)
