# Display strings and Windows integer resources deliberately use different formats.
function(zzlogg_parse_version input)
  if(NOT "${input}" MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?$")
    message(FATAL_ERROR "Version must contain three or four numeric components: ${input}")
  endif()
  string(REPLACE "." ";" components "${input}")
  list(LENGTH components count)
  if(count EQUAL 3)
    list(APPEND components 0)
  endif()
  set(display_parts)
  foreach(index RANGE 0 3)
    list(GET components ${index} number)
    # Avoid octal RC literals such as 09.
    string(REGEX REPLACE "^0+" "" number "${number}")
    if(number STREQUAL "")
      set(number 0)
    endif()
    if(number GREATER 65535)
      message(FATAL_ERROR "Version component exceeds Windows resource range: ${input}")
    endif()
    set(ZZLOGG_VERSION_COMPONENT_${index} "${number}" PARENT_SCOPE)
    if(index LESS 3)
      if(number LESS 10)
        set(number "0${number}")
      endif()
      list(APPEND display_parts "${number}")
    endif()
  endforeach()
  list(JOIN display_parts "." display)
  set(ZZLOGG_DISPLAY_VERSION "${display}" PARENT_SCOPE)
endfunction()
