set(ZZLOGG_UPDATE_STABLE_URL "" CACHE STRING "Production stable signed manifest URL")
set(ZZLOGG_UPDATE_PREVIEW_URL "" CACHE STRING "Production preview signed manifest URL")
set(ZZLOGG_UPDATE_PUBLIC_KEYS "" CACHE STRING "Production keyId:64-lowercase-hex public keys")
set(ZZLOGG_UPDATE_ALLOWED_HOSTS "" CACHE STRING "Exact lowercase update DNS hosts")
set(github_feed_default OFF)
if(DEFINED ENV{ZZLOGG_ENABLE_GITHUB_FEED})
  set(github_feed_default "$ENV{ZZLOGG_ENABLE_GITHUB_FEED}")
endif()
option(ZZLOGG_ENABLE_GITHUB_FEED "Use the official GitHub signed update feed" ${github_feed_default})

function(zzlogg_configure_update_feed output)
  if(ZZLOGG_ENABLE_GITHUB_FEED)
    # Keep defaults local to this function so disabling the option cannot leave
    # stale production URLs/keys in CMakeCache. Explicit custom settings win.
    if(NOT ZZLOGG_UPDATE_STABLE_URL)
      set(ZZLOGG_UPDATE_STABLE_URL "https://raw.githubusercontent.com/jackfahdin/ZzLogg/update-feed/stable.json")
    endif()
    if(NOT ZZLOGG_UPDATE_PREVIEW_URL)
      set(ZZLOGG_UPDATE_PREVIEW_URL "https://raw.githubusercontent.com/jackfahdin/ZzLogg/update-feed/preview.json")
    endif()
    if(NOT ZZLOGG_UPDATE_PUBLIC_KEYS)
      file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../packaging/update/github-public-key.json" public_record)
      string(JSON github_key_id GET "${public_record}" keyId)
      string(JSON github_public_key GET "${public_record}" publicKey)
      set(ZZLOGG_UPDATE_PUBLIC_KEYS "${github_key_id}:${github_public_key}")
    endif()
    if(NOT ZZLOGG_UPDATE_ALLOWED_HOSTS)
      set(ZZLOGG_UPDATE_ALLOWED_HOSTS "raw.githubusercontent.com;github.com;release-assets.githubusercontent.com;objects.githubusercontent.com")
    endif()
  endif()
  set(key_ids "")
  foreach(entry IN LISTS ZZLOGG_UPDATE_PUBLIC_KEYS)
    if(NOT entry MATCHES "^([A-Za-z0-9_-]+):([0-9a-f]+)$")
      message(FATAL_ERROR "Invalid update public key entry")
    endif()
    set(key_id "${CMAKE_MATCH_1}")
    string(LENGTH "${key_id}" id_length)
    string(LENGTH "${CMAKE_MATCH_2}" key_length)
    if(id_length GREATER 64 OR NOT key_length EQUAL 64 OR key_id IN_LIST key_ids)
      message(FATAL_ERROR "Invalid or duplicate update public key ID")
    endif()
    list(APPEND key_ids "${key_id}")
  endforeach()
  foreach(host IN LISTS ZZLOGG_UPDATE_ALLOWED_HOSTS)
    string(LENGTH "${host}" host_length)
    if(host_length GREATER 253 OR NOT host MATCHES "^[a-z0-9.-]+$"
        OR host MATCHES "^\\." OR host MATCHES "\\.$" OR host MATCHES "\\.\\.")
      message(FATAL_ERROR "Invalid update host")
    endif()
    string(REPLACE "." ";" labels "${host}")
    foreach(label IN LISTS labels)
      string(LENGTH "${label}" label_length)
      if(label_length GREATER 63 OR label MATCHES "^-" OR label MATCHES "-$")
        message(FATAL_ERROR "Invalid update DNS label")
      endif()
    endforeach()
  endforeach()
  # Encode instead of inserting caller-controlled strings into C++ literals.
  string(HEX "${ZZLOGG_UPDATE_STABLE_URL}" UPDATE_STABLE_HEX)
  string(HEX "${ZZLOGG_UPDATE_PREVIEW_URL}" UPDATE_PREVIEW_HEX)
  string(HEX "${ZZLOGG_UPDATE_PUBLIC_KEYS}" UPDATE_KEYS_HEX)
  string(HEX "${ZZLOGG_UPDATE_ALLOWED_HOSTS}" UPDATE_HOSTS_HEX)
  string(TIMESTAMP UPDATE_BUILD_TIME "%s" UTC)
  configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/zzlogg_update_feed.h.in" "${output}" @ONLY)
endfunction()
